import { RegisterSucceessParams } from './screen-params.type';

export enum NAVIGATION_KEYS {
	ONBOARDING_FIRST_STEP = 'ONBOARDING_FIRST_STEP',
	ONBOARDING_SECOND_STEP = 'ONBOARDING_SECOND_STEP',
	ONBOARDING_THIRD_STEP = 'ONBOARDING_THIRD_STEP',
	LOGIN = 'LOGIN',
	REGISTER = 'REGISTER',
	REGISTER_SUCCESS = 'REGISTER_SUCCESS',
	HOME = 'HOME',
	SETTINGS = 'SETTINGS',
	PROFILE = 'PROFILE',
}

export type RootStackParamList = {
	[NAVIGATION_KEYS.HOME]: undefined;
	[NAVIGATION_KEYS.ONBOARDING_FIRST_STEP]: undefined;
	[NAVIGATION_KEYS.ONBOARDING_SECOND_STEP]: undefined;
	[NAVIGATION_KEYS.ONBOARDING_THIRD_STEP]: undefined;
	[NAVIGATION_KEYS.LOGIN]: undefined;
	[NAVIGATION_KEYS.REGISTER]: undefined;
	[NAVIGATION_KEYS.REGISTER_SUCCESS]: RegisterSucceessParams;
	[NAVIGATION_KEYS.SETTINGS]: undefined;
	[NAVIGATION_KEYS.PROFILE]: undefined;
};
